### ISSUE TITLE
Optionally return `furl` function rather than attaching it to app as a side effect

### ISSUE THREAD

**Issue by ethanresnick** [paulwalker/connect-static-expiry#16]
Right now, the module's signature is `expiry(app, furl)`. `app` is only used to attach the generated furl function to `app.locals.furl`. 

This api is causing me some small issues, though, and seems like it could be improved a bit. Namely, with the current api, the caller has no way to know from the signature how `app` might be mutated, and no way to avoid the mutation (assigning furl to the local) if it's not desired. In my case, I don't need the app mutation at all (because I'm not using express' built-in templating, and just need to save the generated furl function for use elsewhere). Meanwhile, I have a function that conditionally returns different middleware to use, and it now must take `app` as an argument too, only to pass it down to expiry. That's making its ergonomics a bit clunky. I could generate a new/fake app in the function and pass that to expiry, but I can't do that with any certainty because I don't know that, (eg) in a future version, expiry won't actually need the real app.

So, I want to propose the following:

Expose the furl function as a property of the returned middleware (i.e., `expiry(app, opts).furl`) and then allow the app argument to be `null`; if its null, obviously you don't do `app.locals.furl = furl` assignment. This way, the function still always returns only the middleware, which preserves backwards compatibility while keeping a uniform interface (as opposed to, e.g., sometimes returning a `[middleware, furl]` pair) but it makes the furl function available to callers that don't want to mutate their app. And, by making app essentially optional, makes clear that `app` isn't actually required for the module to do its work.

Thoughts? If this sounds good, I'm happy to work up a branch.

**Comment by paulwalker** [comment]
This sounds fine to me, I never really liked attaching the function to the locals and honestly this was written so long ago when I was fairly new to nodejs. That being said, would you like to be made a core contributor, as I don't even use this in any projects I am working on currently?

**Comment by ethanresnick** [comment]
Sure! Although I think you actually added me as a contributor a while back. I opened this issue because I thought you still might want to weigh in before I made any changes. If you're willing to let me just go at, though, I'll just use my best judgement for things like this in the future.

**Comment by ethanresnick** [comment]
I'm gonna close this since #17's been merged.

@paulwalker is there any particular hold up on getting the module republished on npm? Some way I can help?

**Comment by paulwalker** [comment]
Can you give me an email I can use to add you as an owner of the package on npm?

**Comment by ethanresnick** [comment]
Yup: ethan.resnick@gmail.com

**Comment by paulwalker** [comment]
It looks like i need to do it by your npm user name, have you created one?

**Comment by ethanresnick** [comment]
Yup, it's ethanresnick
