### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by voxpelli** [paulwalker/connect-static-expiry#9]
Thanks for accepting my pull request #8!

I'm currently inclyding the change by linking directly to the git-repostory in my project, but would prefer to point to a released version instead.

If you want help I'm up for helping out with some of the maintaining of this module.

**Comment by paulwalker** [comment]
release 0.0.11, sorry for the delay. would you like to be a core contributor?

**Comment by voxpelli** [comment]
@paulwalker I could certainly help out maintaining the code – fixing bugs etc – if you want such help then feel free to add me to the project here and on npm. I would still prefer to submit any bigger change as a PR to enable others to give feedback on it, but could then merge and release even them myself afterwards.
